# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: yibanAutoSign

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: sginIn
      run: |
        python ./main.py
      env:
        YB_MOBILE: ${{ secrets.YB_MOBILE }}
        YB_PASSWORD: ${{ secrets.YB_PASSWORD }}
        YB_MAIL: ${{ secrets.YB_MAIL }}
        YB_PUSHTOKEN: ${{ secrets.YB_PUSHTOKEN }}
        YB_NOTICE: ${{ secrets.YB_NOTICE }}
        
